### PR TITLE
Add the possibility to send attachments

### PR DESCRIPTION
**Pull request by benDeMtp**
Rocket.chat api sendMessage allow to send attachments with message.
This update allow to add attachments with the rockerSend step.

#Before
`rockerSend message:'My message', channel:'target-channel'`
This command send a preformated message to rocker.chat including build number and job link.

capture d ecran 2017-02-09 a 14 51 01

#Now
There is a backward compatibility. Same command do the same thing.

New step property : 
- rawMessage : Message will not be preformated.
Example :
`rocketSend channel: 'general', message: 'My message', rawMessage: true`

capture d ecran 2017-02-09 a 14 58 27

New message properties :
- alias
- emoji
- avatar
- attachments

Example :
With emoji
`rocketSend channel: 'general', emoji: ':sob:', message: 'My message', rawMessage: true`

capture d ecran 2017-02-09 a 15 01 31

With avatar
`rocketSend avatar: 'http://127.0.0.1:8080/jenkins/static/ff676c77/images/headshot.png', channel: 'general', message: 'My message', rawMessage: true`

capture d ecran 2017-02-09 a 15 03 31

##Attachments
- title : mandatory
- color
- text
- thumbUrl
- messageLink
- collapsed
- authorName
- authorIcon
- authorLink
- titleLink
- titleLinkDownload
- imageUrl
- audioUrl
- videoUrl

`rocketSend attachments: [[audioUrl: '', authorIcon: '', authorName: '', color: 'green', imageUrl: '', messageLink: '', text: 'Build Succes', thumbUrl: '', title: 'my attachment', titleLink: '', titleLinkDownload: '', videoUrl: '']], channel: 'general', message: 'My message', rawMessage: true`

capture d ecran 2017-02-09 a 15 10 14

with many atachments :
`rocketSend attachments: [[audioUrl: '', authorIcon: '', authorName: '', color: 'green', imageUrl: '', messageLink: '', text: 'Build Succes', thumbUrl: '', title: 'my attachment', titleLink: '', titleLinkDownload: '', videoUrl: ''], [audioUrl: '', authorIcon: '', authorName: '', color: 'red', imageUrl: '', messageLink: '', text: 'Something failed', thumbUrl: '', title: 'my other attachment', titleLink: '', titleLinkDownload: '', videoUrl: '']], channel: 'general', message: 'My message', rawMessage: true`

capture d ecran 2017-02-09 a 15 14 22

## GUI update

Update step snippet generator :

capture d ecran 2017-02-09 a 15 17 11

### CODE REVIEW

**Comment by benDeMtp** [comment]
Fix travis error

**Comment by hypery2k** [comment]
thanks for your contribution. But seems with newer RocketChat API it doesn't work

**Comment by benDeMtp** [comment]
Your welcome,

I'm working on the fix, but I have to checkout previous version of rocket.

**Comment by benDeMtp** [comment]
Add method getInfo to retrieve version from server.
Disable attachment, emoji and avatar for server with version lower than "0.50.1"

**Comment by benDeMtp** [comment]
retry

**Comment by benDeMtp** [comment]
thanks you

**Comment by benDeMtp** [comment]
I have not updated the main readme.md
Do you think I have to do it ?

**Comment by hypery2k** [comment]
I will put it in the Jenkins Wiki

**Pull request merged**
