### PR TITLE
Allow to customize server while using rocketSend step

### PR DESCRIPTION
**Pull request by crazy-max**
Closing https://issues.jenkins-ci.org/browse/JENKINS-58315

### CODE REVIEW

**Comment by hypery2k** [comment]
thanks for the PR

**Comment by crazy-max** [comment]
Hi @hypery2k, I will update jelly conf when I've got some time.

**Comment by crazy-max** [comment]
@hypery2k Any ETA for a new release of this plugin please?

**Comment by hypery2k** [comment]
not really, travis build shows errors after adding bugfixing, which i cannot reproduce yet locally: https://travis-ci.org/jenkinsci/rocketchatnotifier-plugin/builds/582528284

**Comment by crazy-max** [comment]
Ok I will try on my computer

**Pull request merged**
